### ISSUE TITLE
Is there a tool to convert hydrogen instrument packs to drumkv1?

### ISSUE THREAD

**Issue by richardhenwood** [marado/drumkv1-audiophob#4]
Hi @marado 

I'm curious if it is feasible to create a tool to convert from hydrogen to drumkv1?

**Comment by marado** [comment]
I did this one manually, but now that I think of it, it should be feasible!

**Comment by marado** [comment]
Turns out someone did it!
https://github.com/TuriSc/hydrogen2drumkv1.py/
